version: "3.8"
services:
  xcliga-client:
    user: node
    image: "naviter/xcliga-client:${IMAGE_TAG}"
    restart: unless-stopped
    ports:
      - 3000:3000
      # outside:container
    env_file:
      - .env
      - .env.local
