version: "3.8"
services:
  xcliga-api:
    user: node
    image: "naviter/xcliga-api:${API_IMAGE_TAG}"
    restart: unless-stopped
    ports:
      - 3030:3030
      # exposed:container
    volumes:
      - ./api/config:/app/config:delegated
      - ./api/data:/app/data:delegated
      - ./api/logs:/app/logs:delegated
    env_file:
      - ./api/.env

  xcliga-client:
    user: node
    image: "naviter/xcliga-client:${CLIENT_IMAGE_TAG}"
    restart: unless-stopped
    ports:
      - 3000:3000
      # exposed:container
    volumes:
      - ./client/.env:/app/.env:delegated
    depends_on:
      - xcliga-api
